### ISSUE TITLE
failed to load cache multi store for height 0

### ISSUE THREAD

**Issue by AiDaiP** [scrtlabs/SecretNetwork#1589]
I'm running local node using the latest release and `./scripts/start-node.sh`, but when I use the client to interact with node, I get an error like this:
```
./secretd tx wasm store "/home/ubuntu22/blockchain/test_cosmwasm/hackatom.wasm" --from a --gas 100000  --fees 100000uscrt -y --chain-id=secretdev-1 --node=http://127.0.0.1:26657 -o json --keyring-backend=test 
Error: rpc error: code = Unknown desc = failed to load cache multi store for height 0: version mismatch on immutable IAVL tree; version does not exist. Version has either been pruned, or is for a future block height
```
I noticed that node output an error when starting, I don’t know if it is related to this.
```
7:11PM ERR CONSENSUS FAILURE!!! err="value is nil" module=consensus stack="goroutine 168 [running]:\nruntime/debug.Stack()\n\t/opt/hostedtoolcache/go/1.21.1/x64/src/runtime/debug/stack.go:24 +0x5e\ngithub.com/tendermint/tendermint/consensus.(*State).receiveRoutine.func2()\n\t/home/runner/go/pkg/mod/github.com/scrtlabs/tendermint@v1.9.0-scrt.0.20230802144651-d62916253d52/consensus/state.go:732 +0x46\npanic({0x19ab700?, 0x27a8720?})\n\t/opt/hostedtoolcache/go/1.21.1/x64/src/runtime/panic.go:914 +0x21f\ngithub.com/cosmos/cosmos-sdk/store/types.AssertValidValue(...)\n\t/home/runner/go/pkg/mod/github.com/scrtlabs/cosmos-sdk@v0.45.13-0.20230802150248-ea64f27dc58d/store/types/validity.go:13\ngithub.com/cosmos/cosmos-sdk/store/gaskv.(*Store).Set(0x36ac3ae?, {0xc00070e2b0?, 0xc0017d4de8?, 0x0?}, {0x0?, 0x0?, 0xc0030da4b0?})\n\t/home/runner/go/pkg/mod/github.com/scrtlabs/cosmos-sdk@v0.45.13-0.20230802150248-ea64f27dc58d/store/gaskv/store.go:51 +0x117\ngithub.com/scrtlabs/SecretNetwork/x/compute/internal/keeper.Keeper.SetRandomSeed({{0x27b3408, 0xc0006f75e0}, {0x27d7120, 0xc0004e77f0}, {0xc0003f6070}, {{0x27b3408, 0xc0006f7510}, {0x27d7120, 0xc0004e77f0}, {{0x27d7120, ...}, ...}, ...}, ...}, ...)\n\t/home/runner/work/SecretNetwork/SecretNetwork/x/compute/internal/keeper/keeper.go:835 +0x299\ngithub.com/scrtlabs/SecretNetwork/x/compute.AppModule.BeginBlock({{}, {{0x27b3408, 0xc0006f75e0}, {0x27d7120, 0xc0004e77f0}, {0xc0003f6070}, {{0x27b3408, 0xc0006f7510}, {0x27d7120, 0xc0004e77f0}, ...}, ...}}, ...)\n\t/home/runner/work/SecretNetwork/SecretNetwork/x/compute/module.go:204 +0x225\ngithub.com/cosmos/cosmos-sdk/types/module.(*Manager).BeginBlock(_, {{0x27c87e8, 0x3766240}, {0x27d6948, 0xc00180b800}, {{0xb, 0x0}, {0xc0030da4b0, 0xb}, 0x1, ...}, ...}, ...)\n\t/home/runner/go/pkg/mod/github.com/scrtlabs/cosmos-sdk@v0.45.13-0.20230802150248-ea64f27dc58d/types/module/module.go:524 +0x198\ngithub.com/scrtlabs/SecretNetwork/app.(*SecretNetworkApp).BeginBlocker(...)\n\t/home/runner/work/SecretNetwork/SecretNetwork/app/app.go:319\ngithub.com/cosmos/cosmos-sdk/baseapp.(*BaseApp).BeginBlock(_, {{0xc001825000, 0x20, 0x20}, {{0xb, 0x0}, {0xc0030da4b0, 0xb}, 0x1, {0x107bdde0, ...}, ...}, ...})\n\t/home/runner/go/pkg/mod/github.com/scrtlabs/cosmos-sdk@v0.45.13-0.20230802150248-ea64f27dc58d/baseapp/abci.go:177 +0x938\ngithub.com/tendermint/tendermint/abci/client.(*localClient).BeginBlockSync(_, {{0xc001825000, 0x20, 0x20}, {{0xb, 0x0}, {0xc0030da4b0, 0xb}, 0x1, {0x107bdde0, ...}, ...}, ...})\n\t/home/runner/go/pkg/mod/github.com/scrtlabs/tendermint@v1.9.0-scrt.0.20230802144651-d62916253d52/abci/client/local_client.go:280 +0x118\ngithub.com/tendermint/tendermint/proxy.(*appConnConsensus).BeginBlockSync(_, {{0xc001825000, 0x20, 0x20}, {{0xb, 0x0}, {0xc0030da4b0, 0xb}, 0x1, {0x107bdde0, ...}, ...}, ...})\n\t/home/runner/go/pkg/mod/github.com/scrtlabs/tendermint@v1.9.0-scrt.0.20230802144651-d62916253d52/proxy/app_conn.go:81 +0x55\ngithub.com/tendermint/tendermint/state.execBlockOnProxyApp({0x27c8890?, 0xc00107a070}, {0x27d0890, 0xc000eb2950}, 0xc00026cd20, {0x27d8080, 0xc000eb6030}, 0x0?, 0x0?)\n\t/home/runner/go/pkg/mod/github.com/scrtlabs/tendermint@v1.9.0-scrt.0.20230802144651-d62916253d52/state/execution.go:364 +0x69f\ngithub.com/tendermint/tendermint/state.(*BlockExecutor).ApplyBlock(_, {{{0xb, 0x0}, {0xc0003f2800, 0x7}}, {0xc0003f2810, 0xb}, 0x1, 0x0, {{0x0, ...}, ...}, ...}, ...)\n\t/home/runner/go/pkg/mod/github.com/scrtlabs/tendermint@v1.9.0-scrt.0.20230802144651-d62916253d52/state/execution.go:158 +0x4a5\ngithub.com/tendermint/tendermint/consensus.(*State).finalizeCommit(0xc0004c7c00, 0x1)\n\t/home/runner/go/pkg/mod/github.com/scrtlabs/tendermint@v1.9.0-scrt.0.20230802144651-d62916253d52/consensus/state.go:1672 +0xb5c\ngithub.com/tendermint/tendermint/consensus.(*State).tryFinalizeCommit(0xc0004c7c00, 0x1)\n\t/home/runner/go/pkg/mod/github.com/scrtlabs/tendermint@v1.9.0-scrt.0.20230802144651-d62916253d52/consensus/state.go:1580 +0x2f6\ngithub.com/tendermint/tendermint/consensus.(*State).enterCommit.func1()\n\t/home/runner/go/pkg/mod/github.com/scrtlabs/tendermint@v1.9.0-scrt.0.20230802144651-d62916253d52/consensus/state.go:1515 +0x9c\ngithub.com/tendermint/tendermint/consensus.(*State).enterCommit(0xc0004c7c00, 0x1, 0x0)\n\t/home/runner/go/pkg/mod/github.com/scrtlabs/tendermint@v1.9.0-scrt.0.20230802144651-d62916253d52/consensus/state.go:1553 +0xc5f\ngithub.com/tendermint/tendermint/consensus.(*State).addVote(0xc0004c7c00, 0xc0012283c0, {0x0, 0x0})\n\t/home/runner/go/pkg/mod/github.com/scrtlabs/tendermint@v1.9.0-scrt.0.20230802144651-d62916253d52/consensus/state.go:2176 +0x17a5\ngithub.com/tendermint/tendermint/consensus.(*State).tryAddVote(0xc0004c7c00, 0xc0012283c0, {0x0?, 0x4c1cb0?})\n\t/home/runner/go/pkg/mod/github.com/scrtlabs/tendermint@v1.9.0-scrt.0.20230802144651-d62916253d52/consensus/state.go:1974 +0x26\ngithub.com/tendermint/tendermint/consensus.(*State).handleMsg(0xc0004c7c00, {{0x27b14c0, 0xc0001b2460}, {0x0, 0x0}})\n\t/home/runner/go/pkg/mod/github.com/scrtlabs/tendermint@v1.9.0-scrt.0.20230802144651-d62916253d52/consensus/state.go:861 +0x3ce\ngithub.com/tendermint/tendermint/consensus.(*State).receiveRoutine(0xc0004c7c00, 0x0)\n\t/home/runner/go/pkg/mod/github.com/scrtlabs/tendermint@v1.9.0-scrt.0.20230802144651-d62916253d52/consensus/state.go:788 +0x4bc\ncreated by github.com/tendermint/tendermint/consensus.(*State).OnStart in goroutine 1\n\t/home/runner/go/pkg/mod/github.com/scrtlabs/tendermint@v1.9.0-scrt.0.20230802144651-d62916253d52/consensus/state.go:379 +0x10c\n"
```
My environment:
```
Intel Xeon Gold 5218R @ 64x 2.095GHz
Ubuntu-22.04.1
```

**Comment by toml01** [comment]
I'd guess it has something to do with the new tm_enclave/random_api libraries.
Do you have all the libs installed correctly in the path and all?

**Comment by AiDaiP** [comment]
I executed scripts/install-everything.sh, but the build failed (#1588 ). Then I try to use the binary from release. Did I miss something related to `tm_enclave/random_api libraries`?
